title: gmx
email: ganzamick@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ganzamick awesome description for your new site here. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rutpasswd

# Build settings
theme: minima
plugins:
  - jekyll-feed

